-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\VHDLGen\MATLAB_Function.vhd
-- Created: 2021-07-19 11:32:16
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: VHDLGen/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function IS
  PORT( oldNco                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        carrErrorDiff                     :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Signals
  SIGNAL oldNco_signed                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL carrErrorDiff_signed             : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL y_tmp                            : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL add_cast                         : signed(69 DOWNTO 0);  -- sfix70_En53
  SIGNAL mul_temp                         : signed(64 DOWNTO 0);  -- sfix65_En53
  SIGNAL add_cast_1                       : signed(63 DOWNTO 0);  -- sfix64_En53
  SIGNAL add_cast_2                       : signed(69 DOWNTO 0);  -- sfix70_En53
  SIGNAL add_temp                         : signed(69 DOWNTO 0);  -- sfix70_En53

BEGIN
  oldNco_signed <= signed(oldNco);

  carrErrorDiff_signed <= signed(carrErrorDiff);

  --carrError
  --tau1carr = fi(1.117551020408163e-04, 0, 32, 32);0
  --PDIcarr = 0;
  --+ carrError * (PDIcarr/tau1carr)
  add_cast <= resize(oldNco_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 70);
  mul_temp <= signed'("010000100011011101011001111100100") * carrErrorDiff_signed;
  
  add_cast_1 <= X"7FFFFFFFFFFFFFFF" WHEN (mul_temp(64) = '0') AND (mul_temp(63) /= '0') ELSE
      X"8000000000000000" WHEN (mul_temp(64) = '1') AND (mul_temp(63) /= '1') ELSE
      mul_temp(63 DOWNTO 0);
  add_cast_2 <= resize(add_cast_1, 70);
  add_temp <= add_cast + add_cast_2;
  
  y_tmp <= X"7FFFFFFF" WHEN ((add_temp(69) = '0') AND (add_temp(68) /= '0')) OR ((add_temp(69) = '0') AND (add_temp(68 DOWNTO 37) = X"7FFFFFFF")) ELSE
      X"80000000" WHEN (add_temp(69) = '1') AND (add_temp(68) /= '1') ELSE
      add_temp(68 DOWNTO 37) + ('0' & add_temp(36));

  y <= std_logic_vector(y_tmp);

END rtl;