-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\VHDLGen\MATLAB_Function1.vhd
-- Created: 2021-07-19 12:30:50
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function1
-- Source Path: VHDLGen/MATLAB Function1
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function1 IS
  PORT( oldNco                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        codeErrorDiff                     :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        codeNco                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En24
        );
END MATLAB_Function1;


ARCHITECTURE rtl OF MATLAB_Function1 IS

  -- Signals
  SIGNAL oldNco_signed                    : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL codeErrorDiff_signed             : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL codeNco_tmp                      : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL add_cast                         : signed(64 DOWNTO 0);  -- sfix65_En52
  SIGNAL mul_temp                         : signed(64 DOWNTO 0);  -- sfix65_En52
  SIGNAL add_cast_1                       : signed(63 DOWNTO 0);  -- sfix64_En52
  SIGNAL add_cast_2                       : signed(64 DOWNTO 0);  -- sfix65_En52
  SIGNAL add_temp                         : signed(64 DOWNTO 0);  -- sfix65_En52

BEGIN
  oldNco_signed <= signed(oldNco);

  codeErrorDiff_signed <= signed(codeErrorDiff);

  add_cast <= resize(oldNco_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 65);
  mul_temp <= signed'("011010011111001000101001100000111") * codeErrorDiff_signed;
  
  add_cast_1 <= X"7FFFFFFFFFFFFFFF" WHEN (mul_temp(64) = '0') AND (mul_temp(63) /= '0') ELSE
      X"8000000000000000" WHEN (mul_temp(64) = '1') AND (mul_temp(63) /= '1') ELSE
      mul_temp(63 DOWNTO 0);
  add_cast_2 <= resize(add_cast_1, 65);
  add_temp <= add_cast + add_cast_2;
  
  codeNco_tmp <= X"7FFFFFFF" WHEN ((add_temp(64) = '0') AND (add_temp(63 DOWNTO 59) /= "00000")) OR ((add_temp(64) = '0') AND (add_temp(59 DOWNTO 28) = X"7FFFFFFF")) ELSE
      X"80000000" WHEN (add_temp(64) = '1') AND (add_temp(63 DOWNTO 59) /= "11111") ELSE
      add_temp(59 DOWNTO 28) + ('0' & add_temp(27));

  codeNco <= std_logic_vector(codeNco_tmp);

END rtl;
