-- VHDL code for codeFreq block


-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\VHDLGen\VHDLGen.vhd
-- Created: 2021-07-19 12:30:50
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: VHDLGen
-- Source Path: VHDLGen
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY VHDLGen IS
  PORT( oldNco                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        codeErrorDiff                     :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
        codeFreq                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En24
        );
END VHDLGen;


ARCHITECTURE rtl OF VHDLGen IS

  -- Component Declarations
  COMPONENT MATLAB_Function1
    PORT( oldNco                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
          codeErrorDiff                   :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En24
          codeNco                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En24
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MATLAB_Function1
    USE ENTITY work.MATLAB_Function1(rtl);

  -- Signals
  SIGNAL codeNco                          : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_MATLAB_Function1 : MATLAB_Function1
    PORT MAP( oldNco => oldNco,  -- sfix32_En24
              codeErrorDiff => codeErrorDiff,  -- sfix32_En24
              codeNco => codeNco  -- sfix32_En24
              );

  codeFreq <= codeNco;

END rtl;