-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\mm_block\Maximum.vhd
-- Created: 2021-07-01 03:28:53
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Maximum
-- Source Path: mm_block/Maximum/mm_block/Maximum
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.mm_block_pkg.ALL;

ENTITY Maximum IS
  PORT( in0                               :   IN    vector_of_std_logic_vector32(0 TO 20);  -- sfix32_En16 [21]
        out0                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        out1                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END Maximum;


ARCHITECTURE rtl OF Maximum IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL in0_signed                       : vector_of_signed32(0 TO 20);  -- sfix32_En16 [21]
  SIGNAL const_idx                        : vector_of_unsigned32(0 TO 20);  -- uint32 [21]
  SIGNAL mm_block_Maximum_treestage1_isgreater : std_logic_vector(0 TO 9);  -- boolean [10]
  SIGNAL mm_block_Maximum_stage1_val      : vector_of_signed32(0 TO 10);  -- sfix32_En16 [11]
  SIGNAL mm_block_Maximum_stage1_idx      : vector_of_unsigned32(0 TO 10);  -- uint32 [11]
  SIGNAL mm_block_Maximum_treestage2_isgreater : std_logic_vector(0 TO 4);  -- boolean [5]
  SIGNAL mm_block_Maximum_stage2_val      : vector_of_signed32(0 TO 5);  -- sfix32_En16 [6]
  SIGNAL mm_block_Maximum_stage2_idx      : vector_of_unsigned32(0 TO 5);  -- uint32 [6]
  SIGNAL mm_block_Maximum_treestage3_isgreater : std_logic_vector(0 TO 2);  -- boolean [3]
  SIGNAL mm_block_Maximum_stage3_val      : vector_of_signed32(0 TO 2);  -- sfix32_En16 [3]
  SIGNAL mm_block_Maximum_stage3_idx      : vector_of_unsigned32(0 TO 2);  -- uint32 [3]
  SIGNAL mm_block_Maximum_treestage4_isgreater : std_logic;
  SIGNAL mm_block_Maximum_stage4_val      : vector_of_signed32(0 TO 1);  -- sfix32_En16 [2]
  SIGNAL mm_block_Maximum_stage4_idx      : vector_of_unsigned32(0 TO 1);  -- uint32 [2]
  SIGNAL mm_block_Maximum_treestage5_isgreater : std_logic;
  SIGNAL mm_block_Maximum_stage5_val      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL mm_block_Maximum_stage5_idx      : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  outputgen: FOR k IN 0 TO 20 GENERATE
    in0_signed(k) <= signed(in0(k));
  END GENERATE;

  const_idx(0) <= to_unsigned(1, 32);
  const_idx(1) <= to_unsigned(2, 32);
  const_idx(2) <= to_unsigned(3, 32);
  const_idx(3) <= to_unsigned(4, 32);
  const_idx(4) <= to_unsigned(5, 32);
  const_idx(5) <= to_unsigned(6, 32);
  const_idx(6) <= to_unsigned(7, 32);
  const_idx(7) <= to_unsigned(8, 32);
  const_idx(8) <= to_unsigned(9, 32);
  const_idx(9) <= to_unsigned(10, 32);
  const_idx(10) <= to_unsigned(11, 32);
  const_idx(11) <= to_unsigned(12, 32);
  const_idx(12) <= to_unsigned(13, 32);
  const_idx(13) <= to_unsigned(14, 32);
  const_idx(14) <= to_unsigned(15, 32);
  const_idx(15) <= to_unsigned(16, 32);
  const_idx(16) <= to_unsigned(17, 32);
  const_idx(17) <= to_unsigned(18, 32);
  const_idx(18) <= to_unsigned(19, 32);
  const_idx(19) <= to_unsigned(20, 32);
  const_idx(20) <= to_unsigned(21, 32);

  ---- Tree max implementation ----
  ---- Tree max stage 1 ----
  
  mm_block_Maximum_treestage1_isgreater(0) <= '1' WHEN in0_signed(0) >= in0_signed(1) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(0) <= in0_signed(0) WHEN mm_block_Maximum_treestage1_isgreater(0) = '1' ELSE
      in0_signed(1);
  
  mm_block_Maximum_stage1_idx(0) <= const_idx(0) WHEN mm_block_Maximum_treestage1_isgreater(0) = '1' ELSE
      const_idx(1);
  
  mm_block_Maximum_treestage1_isgreater(1) <= '1' WHEN in0_signed(2) >= in0_signed(3) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(1) <= in0_signed(2) WHEN mm_block_Maximum_treestage1_isgreater(1) = '1' ELSE
      in0_signed(3);
  
  mm_block_Maximum_stage1_idx(1) <= const_idx(2) WHEN mm_block_Maximum_treestage1_isgreater(1) = '1' ELSE
      const_idx(3);
  
  mm_block_Maximum_treestage1_isgreater(2) <= '1' WHEN in0_signed(4) >= in0_signed(5) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(2) <= in0_signed(4) WHEN mm_block_Maximum_treestage1_isgreater(2) = '1' ELSE
      in0_signed(5);
  
  mm_block_Maximum_stage1_idx(2) <= const_idx(4) WHEN mm_block_Maximum_treestage1_isgreater(2) = '1' ELSE
      const_idx(5);
  
  mm_block_Maximum_treestage1_isgreater(3) <= '1' WHEN in0_signed(6) >= in0_signed(7) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(3) <= in0_signed(6) WHEN mm_block_Maximum_treestage1_isgreater(3) = '1' ELSE
      in0_signed(7);
  
  mm_block_Maximum_stage1_idx(3) <= const_idx(6) WHEN mm_block_Maximum_treestage1_isgreater(3) = '1' ELSE
      const_idx(7);
  
  mm_block_Maximum_treestage1_isgreater(4) <= '1' WHEN in0_signed(8) >= in0_signed(9) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(4) <= in0_signed(8) WHEN mm_block_Maximum_treestage1_isgreater(4) = '1' ELSE
      in0_signed(9);
  
  mm_block_Maximum_stage1_idx(4) <= const_idx(8) WHEN mm_block_Maximum_treestage1_isgreater(4) = '1' ELSE
      const_idx(9);
  
  mm_block_Maximum_treestage1_isgreater(5) <= '1' WHEN in0_signed(10) >= in0_signed(11) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(5) <= in0_signed(10) WHEN mm_block_Maximum_treestage1_isgreater(5) = '1' ELSE
      in0_signed(11);
  
  mm_block_Maximum_stage1_idx(5) <= const_idx(10) WHEN mm_block_Maximum_treestage1_isgreater(5) = '1' ELSE
      const_idx(11);
  
  mm_block_Maximum_treestage1_isgreater(6) <= '1' WHEN in0_signed(12) >= in0_signed(13) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(6) <= in0_signed(12) WHEN mm_block_Maximum_treestage1_isgreater(6) = '1' ELSE
      in0_signed(13);
  
  mm_block_Maximum_stage1_idx(6) <= const_idx(12) WHEN mm_block_Maximum_treestage1_isgreater(6) = '1' ELSE
      const_idx(13);
  
  mm_block_Maximum_treestage1_isgreater(7) <= '1' WHEN in0_signed(14) >= in0_signed(15) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(7) <= in0_signed(14) WHEN mm_block_Maximum_treestage1_isgreater(7) = '1' ELSE
      in0_signed(15);
  
  mm_block_Maximum_stage1_idx(7) <= const_idx(14) WHEN mm_block_Maximum_treestage1_isgreater(7) = '1' ELSE
      const_idx(15);
  
  mm_block_Maximum_treestage1_isgreater(8) <= '1' WHEN in0_signed(16) >= in0_signed(17) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(8) <= in0_signed(16) WHEN mm_block_Maximum_treestage1_isgreater(8) = '1' ELSE
      in0_signed(17);
  
  mm_block_Maximum_stage1_idx(8) <= const_idx(16) WHEN mm_block_Maximum_treestage1_isgreater(8) = '1' ELSE
      const_idx(17);
  
  mm_block_Maximum_treestage1_isgreater(9) <= '1' WHEN in0_signed(18) >= in0_signed(19) ELSE
      '0';
  
  mm_block_Maximum_stage1_val(9) <= in0_signed(18) WHEN mm_block_Maximum_treestage1_isgreater(9) = '1' ELSE
      in0_signed(19);
  
  mm_block_Maximum_stage1_idx(9) <= const_idx(18) WHEN mm_block_Maximum_treestage1_isgreater(9) = '1' ELSE
      const_idx(19);
  mm_block_Maximum_stage1_val(10) <= in0_signed(20);
  mm_block_Maximum_stage1_idx(10) <= const_idx(20);

  ---- Tree max stage 2 ----
  
  mm_block_Maximum_treestage2_isgreater(0) <= '1' WHEN mm_block_Maximum_stage1_val(0) >= mm_block_Maximum_stage1_val(1) ELSE
      '0';
  
  mm_block_Maximum_stage2_val(0) <= mm_block_Maximum_stage1_val(0) WHEN mm_block_Maximum_treestage2_isgreater(0) = '1' ELSE
      mm_block_Maximum_stage1_val(1);
  
  mm_block_Maximum_stage2_idx(0) <= mm_block_Maximum_stage1_idx(0) WHEN mm_block_Maximum_treestage2_isgreater(0) = '1' ELSE
      mm_block_Maximum_stage1_idx(1);
  
  mm_block_Maximum_treestage2_isgreater(1) <= '1' WHEN mm_block_Maximum_stage1_val(2) >= mm_block_Maximum_stage1_val(3) ELSE
      '0';
  
  mm_block_Maximum_stage2_val(1) <= mm_block_Maximum_stage1_val(2) WHEN mm_block_Maximum_treestage2_isgreater(1) = '1' ELSE
      mm_block_Maximum_stage1_val(3);
  
  mm_block_Maximum_stage2_idx(1) <= mm_block_Maximum_stage1_idx(2) WHEN mm_block_Maximum_treestage2_isgreater(1) = '1' ELSE
      mm_block_Maximum_stage1_idx(3);
  
  mm_block_Maximum_treestage2_isgreater(2) <= '1' WHEN mm_block_Maximum_stage1_val(4) >= mm_block_Maximum_stage1_val(5) ELSE
      '0';
  
  mm_block_Maximum_stage2_val(2) <= mm_block_Maximum_stage1_val(4) WHEN mm_block_Maximum_treestage2_isgreater(2) = '1' ELSE
      mm_block_Maximum_stage1_val(5);
  
  mm_block_Maximum_stage2_idx(2) <= mm_block_Maximum_stage1_idx(4) WHEN mm_block_Maximum_treestage2_isgreater(2) = '1' ELSE
      mm_block_Maximum_stage1_idx(5);
  
  mm_block_Maximum_treestage2_isgreater(3) <= '1' WHEN mm_block_Maximum_stage1_val(6) >= mm_block_Maximum_stage1_val(7) ELSE
      '0';
  
  mm_block_Maximum_stage2_val(3) <= mm_block_Maximum_stage1_val(6) WHEN mm_block_Maximum_treestage2_isgreater(3) = '1' ELSE
      mm_block_Maximum_stage1_val(7);
  
  mm_block_Maximum_stage2_idx(3) <= mm_block_Maximum_stage1_idx(6) WHEN mm_block_Maximum_treestage2_isgreater(3) = '1' ELSE
      mm_block_Maximum_stage1_idx(7);
  
  mm_block_Maximum_treestage2_isgreater(4) <= '1' WHEN mm_block_Maximum_stage1_val(8) >= mm_block_Maximum_stage1_val(9) ELSE
      '0';
  
  mm_block_Maximum_stage2_val(4) <= mm_block_Maximum_stage1_val(8) WHEN mm_block_Maximum_treestage2_isgreater(4) = '1' ELSE
      mm_block_Maximum_stage1_val(9);
  
  mm_block_Maximum_stage2_idx(4) <= mm_block_Maximum_stage1_idx(8) WHEN mm_block_Maximum_treestage2_isgreater(4) = '1' ELSE
      mm_block_Maximum_stage1_idx(9);
  mm_block_Maximum_stage2_val(5) <= mm_block_Maximum_stage1_val(10);
  mm_block_Maximum_stage2_idx(5) <= mm_block_Maximum_stage1_idx(10);

  ---- Tree max stage 3 ----
  
  mm_block_Maximum_treestage3_isgreater(0) <= '1' WHEN mm_block_Maximum_stage2_val(0) >= mm_block_Maximum_stage2_val(1) ELSE
      '0';
  
  mm_block_Maximum_stage3_val(0) <= mm_block_Maximum_stage2_val(0) WHEN mm_block_Maximum_treestage3_isgreater(0) = '1' ELSE
      mm_block_Maximum_stage2_val(1);
  
  mm_block_Maximum_stage3_idx(0) <= mm_block_Maximum_stage2_idx(0) WHEN mm_block_Maximum_treestage3_isgreater(0) = '1' ELSE
      mm_block_Maximum_stage2_idx(1);
  
  mm_block_Maximum_treestage3_isgreater(1) <= '1' WHEN mm_block_Maximum_stage2_val(2) >= mm_block_Maximum_stage2_val(3) ELSE
      '0';
  
  mm_block_Maximum_stage3_val(1) <= mm_block_Maximum_stage2_val(2) WHEN mm_block_Maximum_treestage3_isgreater(1) = '1' ELSE
      mm_block_Maximum_stage2_val(3);
  
  mm_block_Maximum_stage3_idx(1) <= mm_block_Maximum_stage2_idx(2) WHEN mm_block_Maximum_treestage3_isgreater(1) = '1' ELSE
      mm_block_Maximum_stage2_idx(3);
  
  mm_block_Maximum_treestage3_isgreater(2) <= '1' WHEN mm_block_Maximum_stage2_val(4) >= mm_block_Maximum_stage2_val(5) ELSE
      '0';
  
  mm_block_Maximum_stage3_val(2) <= mm_block_Maximum_stage2_val(4) WHEN mm_block_Maximum_treestage3_isgreater(2) = '1' ELSE
      mm_block_Maximum_stage2_val(5);
  
  mm_block_Maximum_stage3_idx(2) <= mm_block_Maximum_stage2_idx(4) WHEN mm_block_Maximum_treestage3_isgreater(2) = '1' ELSE
      mm_block_Maximum_stage2_idx(5);

  ---- Tree max stage 4 ----
  mm_block_Maximum_treestage4_isgreater <= hdlcoder_to_stdlogic(mm_block_Maximum_stage3_val(0) >= mm_block_Maximum_stage3_val(1));
  
  mm_block_Maximum_stage4_val(0) <= mm_block_Maximum_stage3_val(0) WHEN mm_block_Maximum_treestage4_isgreater = '1' ELSE
      mm_block_Maximum_stage3_val(1);
  
  mm_block_Maximum_stage4_idx(0) <= mm_block_Maximum_stage3_idx(0) WHEN mm_block_Maximum_treestage4_isgreater = '1' ELSE
      mm_block_Maximum_stage3_idx(1);
  mm_block_Maximum_stage4_val(1) <= mm_block_Maximum_stage3_val(2);
  mm_block_Maximum_stage4_idx(1) <= mm_block_Maximum_stage3_idx(2);

  ---- Tree max stage 5 ----
  mm_block_Maximum_treestage5_isgreater <= hdlcoder_to_stdlogic(mm_block_Maximum_stage4_val(0) >= mm_block_Maximum_stage4_val(1));
  
  mm_block_Maximum_stage5_val <= mm_block_Maximum_stage4_val(0) WHEN mm_block_Maximum_treestage5_isgreater = '1' ELSE
      mm_block_Maximum_stage4_val(1);
  
  mm_block_Maximum_stage5_idx <= mm_block_Maximum_stage4_idx(0) WHEN mm_block_Maximum_treestage5_isgreater = '1' ELSE
      mm_block_Maximum_stage4_idx(1);

  out0 <= std_logic_vector(mm_block_Maximum_stage5_val);

  out1 <= std_logic_vector(mm_block_Maximum_stage5_idx);

END rtl;

